# Generated by Django 5.0.6 on 2024-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', help_text="Enter the book's language", max_length=30),
        ),
    ]
